### ISSUE TITLE
add MLAOI extension example

### ISSUE THREAD

**Issue by rbavery** [crim-ca/dlm-extension#11]
> Consider adding ml-aoi:split: train to make an explicit reference that this corresponds to the training samples used for generating the model (see https://cloudnativegeo.slack.com/archives/C06559H0UUQ/p1710265427364609?thread_ts=1710251736.833979&cid=C06559H0UUQ).
> 
> A title mentioning this could be relevant also to make the example link more obvious by inexperienced users with all the STAC extensions involved.
> 
> I think this capability definitely merits an improved add_derived_from optional parameter to help users generate the item (ml_aoi_split: ML_AOI_Split = None ?).
> for the type, see: https://github.com/stac-extensions/ml-aoi/pull/8/files#diff-2c01497f2468c2d24ba1055b1df7c2e3fe570e38c3b0804dee337c199c259024R66

**Comment by fmigneault** [comment]
Provided in the examples. 
For example: https://github.com/crim-ca/mlm-extension/blob/2a2bac7a8ae04bba6131149440bd1f7068b9233a/examples/item_multi_io.json#L270
Also, described in https://github.com/crim-ca/mlm-extension/blob/main/best-practices.md#ml-aoi-and-label-extensions
